[project]
name = "Aquatic-Weeds-Programme"
version = "0.0.0"
dependencies = ["dash==2.17.0", "plotly==5.22.0", "pandas==2.2.1"]

[tool.pylint]
max-line-length = "120"

[tool.isort]
profile = "black"
line_ending = "LF"
ensure_newline_before_comments = true
